=== JoshuaBehrens/phpunuhi/tests/playground/xsd/phpunuhi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="phpunuhi" type="phpunuhiType"/>
  <xs:complexType name="envType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="phpType" mixed="true">
    <xs:sequence>
      <xs:element type="envType" name="env" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="indent" use="optional"/>
    <xs:attribute type="xs:string" name="sort" use="optional"/>
  </xs:complexType>
  <xs:complexType name="jsonType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="indent"/>
        <xs:attribute type="xs:string" name="sort"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="formatType">
    <xs:sequence>
      <xs:element type="jsonType" name="json" minOccurs="0"/>
      <xs:element type="iniType" name="ini" minOccurs="0"/>
      <xs:element type="phpType" name="php" minOccurs="0"/>
      <xs:element type="shopware6Type" name="shopware6" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="localeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="iniSection" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="localesType">
    <xs:sequence>
      <xs:element type="localeType" name="locale" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="setType">
    <xs:sequence>
      <xs:element type="formatType" name="format"/>
      <xs:element type="filterType" name="filter" minOccurs="0"/>
      <xs:element type="localesType" name="locales"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="iniType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="sort"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="shopware6Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="entity"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="includeType">
    <xs:sequence>
      <xs:element type="xs:string" name="key"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="excludeType">
    <xs:sequence>
      <xs:element type="xs:string" name="key"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="filterType">
    <xs:sequence>
      <xs:element type="includeType" name="include"/>
      <xs:element type="excludeType" name="exclude"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="translationsType">
    <xs:sequence>
      <xs:element type="setType" name="set" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="phpunuhiType">
    <xs:sequence>
      <xs:element type="phpType" name="php"/>
      <xs:element type="translationsType" name="translations"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== JoshuaBehrens/phpunuhi/tests/playground/xsd/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="phpunuhi.xsd"
>

    <php>
        <env name="DB_HOST" value="127.0.0.1"/>
        <env name="DB_PORT" value="3306"/>
        <env name="DB_USER" value=""/>
        <env name="DB_PASSWD" value=""/>
        <env name="DB_DBNAME" value=""/>
    </php>

    <translations>

        <set name="json">
            <format>
                <json indent="2" sort="true"/>
            </format>
            <locales>
                <locale name="de">./snippets/storefront/de.json</locale>
                <locale name="en">./snippets/storefront/en.json</locale>
            </locales>
        </set>

        <set name="ini">
            <format>
                <ini sort="true"/>
            </format>
            <locales>
                <locale name="de" iniSection="de">./snippets/storefront/de.json</locale>
                <locale name="en" iniSection="en">./snippets/storefront/en.json</locale>
            </locales>
        </set>

        <set name="php">
            <format>
                <php indent="2" sort="true"/>
            </format>
            <locales>
                <locale name="de">./snippets/storefront/de.php</locale>
                <locale name="en">./snippets/storefront/en.php</locale>
            </locales>
        </set>

        <set name="shopware6">
            <format>
                <shopware6 entity="product"/>
            </format>
            <filter>
                <include>
                    <key>abc</key>
                </include>
                <exclude>
                    <key>abc</key>
                </exclude>
            </filter>
            <locales>
                <locale name="de"/>
                <locale name="en"/>
            </locales>
        </set>

    </translations>

</phpunuhi>

=== JoshuaBehrens/phpunuhi/tests/playground/php/phpunuhi.xml
<phpunuhi
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../xsd/phpunuhi.xsd"
>

    <translations>

        <set name="php">
            <format>
                <php sort="true"/>
            </format>
            <locales>
                <locale name="de">./de.php</locale>
                <locale name="en">./en.php</locale>
            </locales>
        </set>

    </translations>

</phpunuhi>
